import ReportCharts from "../reports/ReportCharts";
import ChapterMasteryProgression from "../reports/ChapterMasteryProgression";
import SmartQuizStats from "../reports/SmartQuizStats";
import StudentInsights from "../reports/StudentInsights";
import { Student } from "@/api/mockStudents";
import Image from "next/image";

interface ReportCardProps {
  student: Student;
}

const ReportCard = ({ student }: ReportCardProps) => {
  return (
    <div className="bg-white text-black space-y-6">
      <header className="flex items-center justify-between border-b pb-4 mb-6">
        {/* Logo and Title */}
        <div className="flex items-center space-x-3">
          <div className="relative w-12 h-12">
            <Image
              src="/logo-square.svg"
              layout="fill"
              objectFit="contain"
              priority
              alt="Logo"
            />
          </div>
          <div>
            <h1 className="text-2xl font-bold">Student Report</h1>
            <p className="text-sm text-gray-600">Generated by AI Need Help</p>
            <p className="text-sm text-indigo-600 font-semibold">
              Subject: {student.subject}
            </p>
          </div>
        </div>

        {/* Student Info */}
        <div className="text-right space-y-1">
          <p className="text-lg font-medium text-gray-800">
            Name: {student.name}
          </p>
          <p className="text-sm text-gray-500">ID: {student.id}</p>
        </div>
      </header>

      <section>
        <h2 className="text-xl font-semibold mb-2">
          Learning Objective Progression
        </h2>

        {/* no param because inside have mock data */}
        <ReportCharts />
      </section>
      <section>
        <h2 className="text-xl font-semibold mb-2">Mastery Checklist</h2>
        <ChapterMasteryProgression checklist={student.masteryChecklist} />
      </section>
      <section>
        <h2 className="text-xl font-semibold mb-2">
          AI Feedback & Student Insights
        </h2>
        <StudentInsights insights={student.llmComments} />
      </section>
      <section>
        <h2 className="text-xl font-semibold mb-2">Smart Quiz Performance</h2>
        <SmartQuizStats stats={student.smartQuizStats} />
      </section>
    </div>
  );
};

export default ReportCard;
