import type { Metadata } from "next";
<<<<<<< HEAD
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
=======
import { Onest } from "next/font/google";
import NavBar from "@/components/nav-bar/NavBar";
import "./globals.css";
import { SmartQuizProvider } from "@/context/SmartQuizContext";

const onest = Onest({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-onest",
>>>>>>> origin/main
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<<<<<<< HEAD
    <html lang="en" className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
=======
    <html lang="en" className={`${onest.variable} h-full`}>
      <body className="font-onest bg-white">
        <SmartQuizProvider>
          <NavBar />

          <main className="flex-1 pl-20 h-full">{children}</main>
        </SmartQuizProvider>
>>>>>>> origin/main
      </body>
    </html>
  );
}
