import type { Metadata } from "next";
import { Onest } from "next/font/google";
import "./globals.css";
import { SmartQuizProvider } from "@/context/SmartQuizContext";
import { SubjectDataProvider } from "@/context/SubjectDataContext";
import { AssistantChatProvider } from "@/context/AssistantChatContext";
import { UserProvider } from "@/context/UserContext";
import ConditionalLayout from "@/components/ConditionalLayout";
import { Toaster } from "react-hot-toast";

const onest = Onest({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-onest",
});

export const metadata: Metadata = {
  title: "AI Need Help",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${onest.variable} h-full`}>
      <body className="font-onest bg-white">
        <UserProvider>
          <SmartQuizProvider>
            <AssistantChatProvider>
              <SubjectDataProvider>
                <ConditionalLayout>{children}</ConditionalLayout>
                <Toaster
                  position="top-center"
                  toastOptions={{ duration: 3000 }}
                />
              </SubjectDataProvider>
            </AssistantChatProvider>
          </SmartQuizProvider>
        </UserProvider>
      </body>
    </html>
  );
}
